
name: test_urls
on:  
  workflow_dispatch:
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"
# cron job runs every day

jobs:
    ping_urls:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install testing dependencies
        run: |
          pip install .[tests]

      - name: test urls
        run: |
          pytest -v tests/tests_urls.py
