
name: test_convert_scripts
on:  
  workflow_dispatch:
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main


jobs:
    run_scripts:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v19
        with:
          files: |
            openmc_data/convert_*.py

      - name: Set up Python
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install testing dependencies
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sudo apt-get install libhdf5-serial-dev
          git clone --single-branch --branch develop --depth 1 https://github.com/openmc-dev/openmc.git
          cd openmc
          mkdir build
          cd build
          cmake ..
          make -j2
          sudo make -j2 install
          cd ..
          pip install .
          cd ..
          pip install .

      - name: test default convert_fendl
        if: contains(steps.changed-files-specific.outputs.modified_files, 'openmc_data/convert_fendl.py')
        run: |
          echo "openmc_data/convert_fendl.py file has been modified."
          convert_fendl
