
name: test_package
on:  
  workflow_dispatch:
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main


jobs:
    run_scripts:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install testing dependencies
        run: |
          pip install .[tests]

      - name: Test scripts exist
        run: |
          python convert_fendl
