
name: test_package
on:  
  workflow_dispatch:
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main


jobs:
    run_scripts:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install testing dependencies
        run: |
          sudo apt-get install libhdf5-serial-dev
          git clone --single-branch --branch develop --depth 1 https://github.com/openmc-dev/openmc.git
          cd openmc
          mkdir build
          cd build
          cmake ..
          make -j2
          sudo make -j2 install
          cd ..
          pip install .
          cd ..
          pip install .

      - name: Test scripts exist
        run: |
          convert_fendl --help
          convert_tendl --help
          convert_jeff32 --help
